spring:
  profiles:
    active: test

  # =============================
  # Embedded MongoDB
  # =============================
  data:
    mongodb:
      database: media_service_test
      port: 0

  mongodb:
    embedded:
      version: 7.0.4

# =============================
# Disable Eureka
# =============================
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# =============================
# Server
# =============================
server:
  port: 0

# =============================
# Logging
# =============================
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: WARN
