# =============================
# application-test.yml (api-gateway)
# =============================

spring:
  main:
    web-application-type: reactive

  cloud:
    discovery:
      enabled: false

# =============================
# DISABLE EUREKA COMPLETELY
# =============================
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# =============================
# SERVER
# =============================
server:
  port: 0

# =============================
# LOGGING
# =============================
logging:
  level:
    root: INFO
    com.netflix.discovery: OFF
    org.springframework.cloud.netflix: OFF
